extends: configs/dam_2d/base.yaml

model: 
  name: cconv
  input_seq_length: 3
  vel_div_loss: False
  positions_after_forces: True
train:
  noise_std: 0.0
  optimizer:
    lr_start: 5.e-4
  loss_weight:
    pos: 1.0
    vel: 0.0
    acc: 0.0
