extends: configs/rpf_2d/base.yaml

model: 
  name: egnn
  num_mp_steps: 5
  latent_dim: 128
  isotropic_norm: True
  magnitude_features: True

train:
  optimizer:
    lr_start: 5.e-4
  loss_weight:
    pos: 1.0
    vel: 0.0
    acc: 0.0
